### PR TITLE
Added support for densitytensor simulations!

### PR DESCRIPTION
**Pull request by SamDuffield**

### CODE REVIEW

**Review by gamatos — APPROVED** [review]
Looks good, could maybe also add a note about mixed state simulations in `README.md`.

**Comment by SamDuffield** [comment]
> Looks good, could maybe also add a note about mixed state simulations in `README.md`.

I have added a short note in the README saying qujax also supports densitytensor simulations inc mixed states and Kraus operators, WDYT?

**Comment by gamatos** [comment]
I think having a short code snippet with usage, or making it clear which functions correspond to density matrix simulations (i.e. `get_params_to_statetensor_func` > `get_params_to_densitytensor_func`, or having a notebook with density matrix specific examples, would be better. But those are things that can be added later, so I'm not opposed to it being merged as is.

**Comment by SamDuffield** [comment]
> I think having a short code snippet with usage, or making it clear which functions correspond to density matrix simulations (i.e. `get_params_to_statetensor_func` > `get_params_to_densitytensor_func`, or having a notebook with density matrix specific examples, would be better. But those are things that can be added later, so I'm not opposed to it being merged as is.

yes totally agree, particularly on the notebook front. I think we can merge this and then create an issue describing what a notebook could include.

**Pull request merged**
