### PR TITLE
Bump version to 1.1.0

### PR DESCRIPTION
**Pull request by gamatos**

### CODE REVIEW

**Comment by cqc-melf** [comment]
Do you want to merge this to develop or into main?

**Comment by gamatos** [comment]
I think we should do develop first and then main so we ensure both branches are in sync, last time we did it directly into main and we had to go back for a commit that got left behind in develop, so this seems safer. What do you think?

**Comment by cqc-melf** [comment]
I think it is both fine here.

On bigger projects it could happen that there are commits added to develop during the release process which could mess things up. I would not expect this to happen here.

**Review by cqc-melf — APPROVED** [review]

**Comment by gamatos** [comment]
I see, that is a good point. But it might still be good to bump the version both in `develop` and in `main`.

I guess we could just separately merge the version bump (which is all this branch is) into develop and into main, as opposed to merging into develop and then develop into main. 

Though as you say it probably it is very unlikely that it will matter for this project.

**Pull request merged**
