### PR TITLE
Update and restructure documentation

### PR DESCRIPTION
**Pull request by gamatos**
- Restructure contents by grouping statetensor, utility functions 
- Add `all_zeros_statetensor`, `all_zeros_densitytensor` to documentation 
- Add `repeat_circuit` to documentation

### CODE REVIEW

**Comment by cqc-melf** [comment]
Have you checked if the documentation still builds correctly?

**Comment by gamatos** [comment]
> Have you checked if the documentation still builds correctly?

Seems to build fine for me locally!

**Review by cqc-melf — APPROVED** [review]
Looks good :)

**Comment by gamatos** [comment]
Awesome!

**Pull request merged**
